format = """
[▓▒░](#3c3836)\
[ 󰣇 ](bg:#282828 fg:#d65d0e)\
[](bg:#d65d0e fg:#282828)\
$directory\
[](fg:#d65d0e bg:#1d2021)\
$git_branch\
$git_status\
[](fg:#1d2021 bg:#1d2021)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#1d2021 bg:#1d2230)\
$time\
[ ](fg:#282828)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#d65d0e"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#1d2021"
format = '[[ $symbol $branch ](fg:#d65d0e bg:#1d2021)]($style)'

[git_status]
style = "bg:#1d2021"
format = '[[($all_status$ahead_behind )](fg:#d65d0e bg:#1d2021)]($style)'

[nodejs]
symbol = ""
style = "bg:#1d2021"
format = '[[ $symbol ($version) ](fg:#d65d0e bg:#1d2021)]($style)'

[rust]
symbol = ""
style = "bg:#1d2021"
format = '[[ $symbol ($version) ](fg:#d65d0e bg:#1d2021)]($style)'

[golang]
symbol = ""
style = "bg:#1d2021"
format = '[[ $symbol ($version) ](fg:#d65d0e bg:#1d2021)]($style)'

[php]
symbol = ""
style = "bg:#1d2021"
format = '[[ $symbol ($version) ](fg:#d65d0e bg:#1d2021)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
